(function () {
  const STORAGE_KEY = "trama-bncc-v1";
  const initial = { plans: [], classes: [], assessments: [], pdis: [] };
  let state = load();
  let currentPlan = null;

  function load(){ try { return {...initial, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")} } catch { return structuredClone(initial) } }
  function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); updateAll(); }
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const esc = (v="") => String(v).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const normalize = s => s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const uid = () => Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  function toast(message){ const t=$("#toast"); t.textContent=message; t.classList.add("show"); setTimeout(()=>t.classList.remove("show"),2600); }

  function navigate(view){
    $$(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));
    $$(".nav-item[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view));
    const labels={inicio:"Visão geral",planejar:"Planejar aula",bncc:"Explorar BNCC",planos:"Meus planos",turmas:"Turmas",avaliar:"Avaliar",relatorios:"Relatórios",pdi:"PDI pedagógico",dados:"Backup e dados"};
    $("#page-title").textContent=labels[view]||"Trama"; document.body.classList.remove("menu-open"); updateAll(); window.scrollTo({top:0,behavior:"smooth"});
  }
  $$("[data-view]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.view)));
  $$("[data-go]").forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.go)));
  $(".mobile-menu").addEventListener("click",()=>document.body.classList.toggle("menu-open"));

  function matchTopic(topic, component, year){
    const n=normalize(topic); const y=Number(year);
    const matches=window.TRAMA_DATA.topics.filter(x => x.terms.some(t=>n.includes(normalize(t))) && (x.component==="*"||x.component===component) && x.years.includes(y));
    return matches[0] || null;
  }
  function recommendComputing(topic, year){
    const aliases={"fake":["veracidade","credibilidade"],"bullying":["cyberbullying"],"senha":["segurança","proteção","criptografia"],"programar":["programação","algoritmo"],"programacao":["programação","algoritmo"],"arquivo":["arquivos","documentos","metadados"],"rede":["internet","transmissão","redes sociais"],"ambiente":["sustentabilidade","socioambientais"],"autoria":["direitos autorais","publicar","conteúdo"]};
    const words=normalize(topic).split(/\W+/).filter(w=>w.length>2); const expanded=[...words,...words.flatMap(w=>(aliases[w]||[]).flatMap(x=>normalize(x).split(/\W+/)))];
    return window.TRAMA_DATA.computingSkills.filter(([,years])=>years.includes(Number(year))).map(([code,years,axis,text])=>({code,axis,text,score:expanded.reduce((n,w)=>n+(normalize(`${code} ${axis} ${text}`).includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code)).slice(0,3);
  }
  function recommendSubject(topic, component, year){
    const aliases={"fake":["veracidade","credibilidade","fontes"],"programacao":["algoritmo","tecnologia"],"programar":["algoritmo","tecnologia"],"coordenada":["plano cartesiano"],"midia":["mídias","multissemiótico"],"ambiente":["ambiental","sustentabilidade"],"mapa":["cartográfico","cartografia"],"dados":["tabelas","gráficos","informações"]};
    const words=normalize(topic).split(/\W+/).filter(w=>w.length>2); const expanded=[...words,...words.flatMap(w=>(aliases[w]||[]).flatMap(x=>normalize(x).split(/\W+/)))];
    return (window.TRAMA_CURRICULUM?.records||[]).filter(x=>x.component===component&&x.years.includes(Number(year))).map(x=>({...x,score:expanded.reduce((n,w)=>n+(normalize(`${x.code} ${x.text}`).includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code)).slice(0,4);
  }
  $("#planner-form").addEventListener("submit", e=>{
    e.preventDefault(); const topic=$("#topic").value.trim(), year=$("#year").value, component=$("#component").value;
    const found=matchTopic(topic,component,year); const d=found||window.TRAMA_DATA.defaults; const recommended=recommendComputing(topic,year); const subjectMatches=recommendSubject(topic,component,year); const computing=found?.computing||(recommended.length?recommended.slice(0,2).map(({code,axis,text})=>({code,axis,text})):d.computing); const subject=found?.subject||(subjectMatches[0]?{code:subjectMatches[0].code,text:subjectMatches[0].text}:{code:"Revisão necessária",text:`Nenhuma habilidade de ${component} apresentou correspondência textual suficiente para “${topic}”.`});
    currentPlan={id:uid(),createdAt:new Date().toISOString(),topic,year,component,lessons:$("#lessons").value,duration:$("#duration").value,mode:$("input[name=mode]:checked").value,resources:$("#resources").value,notes:$("#class-notes").value,transversal:$("#transversal").checked,subject,subjectAlternatives:subjectMatches.slice(found?0:1,4),computing,alternatives:recommended.slice(1),confidence:found?.confidence||((recommended.length&&subjectMatches.length)?"Correspondência temática sugerida":"Aproximação pedagógica"),tech:d.tech,unplugged:d.unplugged,project:d.project};
    renderGenerated(currentPlan); $("#generated-plan").scrollIntoView({behavior:"smooth",block:"start"});
  });
  function renderGenerated(p){
    $("#generated-plan").innerHTML=`<article class="plan-result"><div class="result-head"><div><span class="confidence">${esc(p.confidence)}</span><h2>${esc(p.topic)}</h2><p>${esc(p.year)}º ano · ${esc(p.component)} · ${esc(p.lessons)} aula(s) de ${esc(p.duration)}</p></div><button id="save-plan" class="primary">Salvar plano</button></div>
    <div class="connection"><div class="skill subject"><span>${esc(p.component)}</span><strong>${esc(p.subject.code)}</strong><p>${esc(p.subject.text)}</p></div><div class="connector">↔<small>${esc(p.confidence)}</small></div><div class="skill computing"><span>BNCC Computação</span><strong>${esc(p.computing[0].code)}</strong><p>${esc(p.computing[0].text)}</p></div></div>
    ${p.subjectAlternatives?.length?`<div class="alternatives"><span>OUTRAS HABILIDADES DE ${esc(p.component).toUpperCase()}</span>${p.subjectAlternatives.map(a=>`<small><b>${esc(a.code)}</b></small>`).join("")}</div>`:""}
    ${p.alternatives?.length?`<div class="alternatives"><span>OUTRAS HABILIDADES DE COMPUTAÇÃO</span>${p.alternatives.map(a=>`<small><b>${esc(a.code)}</b> · ${esc(a.axis)}</small>`).join("")}</div>`:""}
    <div class="plan-section"><span class="eyebrow">OBJETIVOS</span><ul><li>Compreender e aplicar conceitos de <strong>${esc(p.topic)}</strong> em uma situação significativa.</li><li>Planejar uma solução por etapas, testar resultados e comunicar decisões.</li><li>Relacionar a habilidade de ${esc(p.component)} ao eixo ${esc(p.computing[0].axis)}.</li></ul></div>
    <div class="paths"><article><span class="path-number">A</span><div><span class="eyebrow">COM TECNOLOGIA</span><h3>Construir, testar e explicar</h3><p>${esc(p.tech)}</p><small>Recursos: ${esc(p.resources||"recursos digitais disponíveis")}</small></div></article><article><span class="path-number">B</span><div><span class="eyebrow">SEM TECNOLOGIA</span><h3>Representar, executar e depurar</h3><p>${esc(p.unplugged)}</p><small>Mesmos objetivos e evidências da trilha tecnológica.</small></div></article></div>
    ${p.transversal?`<div class="project-box"><span>PROJETO TRANSVERSAL</span><h3>${esc(p.project)}</h3><p>Produto final coletivo com registro individual de autoria e reflexão.</p></div>`:""}
    <div class="plan-section"><span class="eyebrow">SEQUÊNCIA DIDÁTICA</span><ol class="timeline"><li><b>Disparador</b><span>Apresente um problema relacionado ao assunto e recolha hipóteses iniciais.</span></li><li><b>Modelagem</b><span>Identifique entradas, regras, decisões e resultados esperados.</span></li><li><b>Construção</b><span>Realize a trilha tecnológica ou desplugada em pequenos grupos.</span></li><li><b>Teste e revisão</b><span>Troque as produções entre grupos e registre o que precisou ser corrigido.</span></li><li><b>Socialização</b><span>Cada estudante explica uma decisão e registra uma evidência individual.</span></li></ol></div>
    <div class="plan-section"><span class="eyebrow">RUBRICA DE EVIDÊNCIAS</span><div class="rubric-preview"><span>Conteúdo curricular</span><span>Pensamento computacional</span><span>Autoria</span><span>Comunicação</span><span>Colaboração</span></div><p class="muted">Escala: 1 Inicial · 2 Em desenvolvimento · 3 Adequado · 4 Avançado · N/O Não observado</p></div>
    <div class="source-note">Base local: ${esc(window.TRAMA_DATA.version)}. Correspondências são justificadas e devem ser revisadas pelo professor antes da aplicação.</div></article>`;
    $("#save-plan").addEventListener("click",()=>{ if(!state.plans.some(x=>x.id===p.id)) state.plans.unshift(p); save(); toast("Plano salvo neste dispositivo."); navigate("planos"); });
  }

  $("#class-form").addEventListener("submit",e=>{e.preventDefault();const year=$("#class-year").value,letter=$("#class-letter").value.trim().toUpperCase(),size=Number($("#class-size").value);const code=`${year}${letter}`;if(state.classes.some(c=>c.code===code))return toast("Essa turma já existe.");state.classes.push({id:uid(),code,year,letter,size,students:Array.from({length:size},(_,i)=>`${code}-${String(i+1).padStart(2,"0")}`)});save();toast("Turma criada com identificadores numéricos.");});
  function renderPlans(){const host=$("#plans-list");host.innerHTML=state.plans.length?state.plans.map(p=>`<article class="list-card"><div><span class="confidence">${esc(p.confidence)}</span><h3>${esc(p.topic)}</h3><p>${esc(p.year)}º ano · ${esc(p.component)} · ${esc(p.computing[0].code)}</p></div><div class="card-actions"><button class="secondary open-plan" data-id="${p.id}">Abrir</button><button class="icon-button delete-plan" data-id="${p.id}" aria-label="Excluir plano">×</button></div></article>`).join(""):`<div class="empty"><span>▤</span><h3>Nenhum plano salvo</h3><p>Gere sua primeira conexão curricular.</p><button class="primary" data-empty-go="planejar">Criar plano</button></div>`;$$('[data-empty-go]',host).forEach(b=>b.onclick=()=>navigate(b.dataset.emptyGo));$$(".open-plan",host).forEach(b=>b.onclick=()=>{currentPlan=state.plans.find(p=>p.id===b.dataset.id);navigate("planejar");renderGenerated(currentPlan)});$$(".delete-plan",host).forEach(b=>b.onclick=()=>{state.plans=state.plans.filter(p=>p.id!==b.dataset.id);save();toast("Plano removido.")});}
  function renderClasses(){const host=$("#classes-list");host.innerHTML=state.classes.length?state.classes.map(c=>`<article class="list-card class-card"><div><span class="eyebrow">TURMA</span><h3>${esc(c.year)}º ${esc(c.letter)}</h3><p>${c.size} identificadores · ${esc(c.students[0])} a ${esc(c.students.at(-1))}</p></div><button class="icon-button delete-class" data-id="${c.id}" aria-label="Excluir turma">×</button></article>`).join(""):`<div class="empty compact"><span>◎</span><h3>Crie a primeira turma</h3><p>Os identificadores serão gerados automaticamente.</p></div>`;$$(".delete-class",host).forEach(b=>b.onclick=()=>{if(confirm("Excluir esta turma e os registros associados?")){const c=state.classes.find(x=>x.id===b.dataset.id);state.classes=state.classes.filter(x=>x.id!==b.dataset.id);state.assessments=state.assessments.filter(x=>x.classId!==c.id);state.pdis=state.pdis.filter(x=>x.classId!==c.id);save()}});}
  function fillSelect(el,items,label,value){const prev=el.value;el.innerHTML=items.length?items.map(x=>`<option value="${esc(value(x))}">${esc(label(x))}</option>`).join(""):`<option value="">Nenhum registro disponível</option>`;if([...el.options].some(o=>o.value===prev))el.value=prev;}
  function syncSelectors(){["assessment-class","report-class","pdi-class"].forEach(id=>fillSelect($("#"+id),state.classes,c=>`${c.year}º ${c.letter}`,c=>c.id));fillSelect($("#assessment-plan"),state.plans,p=>`${p.topic} · ${p.year}º`,p=>p.id);syncStudents("report");syncStudents("pdi");}
  function syncStudents(prefix){const cls=state.classes.find(c=>c.id===$("#"+prefix+"-class").value);fillSelect($("#"+prefix+"-student"),cls?.students||[],s=>s,s=>s);}
  $("#report-class").addEventListener("change",()=>{syncStudents("report");renderReport()});$("#report-student").addEventListener("change",renderReport);$("#pdi-class").addEventListener("change",()=>{syncStudents("pdi");loadPdi()});$("#pdi-student").addEventListener("change",loadPdi);
  $("#load-rubric").addEventListener("click",()=>{const cls=state.classes.find(c=>c.id===$("#assessment-class").value),plan=state.plans.find(p=>p.id===$("#assessment-plan").value);const host=$("#rubric-form");if(!cls||!plan)return toast("Crie uma turma e salve um plano primeiro.");host.innerHTML=`<div class="rubric-head"><div><span class="eyebrow">${esc(cls.code)} · ${esc(plan.topic)}</span><h3>Registro rápido</h3></div><button class="primary" type="submit">Salvar avaliação</button></div><div class="rubric-table"><div class="rubric-row header"><span>Estudante</span><span>Currículo</span><span>Computação</span><span>Autoria</span><span>Comunicação</span><span>Colaboração</span></div>${cls.students.map(s=>`<div class="rubric-row" data-student="${s}"><strong>${s}</strong>${["curriculum","computing","authorship","communication","collaboration"].map(k=>`<select aria-label="${k} de ${s}" data-key="${k}"><option value="NO">N/O</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select>`).join("")}</div>`).join("")}</div><label>Observação geral da aplicação<textarea id="assessment-note" rows="3" placeholder="O que funcionou? O que precisa ser retomado?"></textarea></label>`;host.dataset.classId=cls.id;host.dataset.planId=plan.id;});
  $("#rubric-form").addEventListener("submit",e=>{e.preventDefault();const rows=$$(".rubric-row[data-student]",e.currentTarget);if(!rows.length)return;const scores=rows.map(r=>({student:r.dataset.student,...Object.fromEntries($$("select",r).map(s=>[s.dataset.key,s.value]))}));state.assessments.push({id:uid(),date:new Date().toISOString(),classId:e.currentTarget.dataset.classId,planId:e.currentTarget.dataset.planId,note:$("#assessment-note")?.value||"",scores});save();toast("Avaliação salva.");navigate("relatorios");});
  function renderReport(){const student=$("#report-student").value,cls=state.classes.find(c=>c.id===$("#report-class").value),host=$("#report-output");if(!student||!cls){host.innerHTML=`<div class="empty"><span>↗</span><h3>Sem relatório disponível</h3><p>Cadastre uma turma e registre uma avaliação.</p></div>`;return}const records=state.assessments.filter(a=>a.classId===cls.id).flatMap(a=>{const score=a.scores.find(s=>s.student===student);return score?[{...score,assessment:a,plan:state.plans.find(p=>p.id===a.planId)}]:[]});const dims=["curriculum","computing","authorship","communication","collaboration"],labels={curriculum:"Conteúdo curricular",computing:"Pensamento computacional",authorship:"Autoria",communication:"Comunicação",collaboration:"Colaboração"};const avg=Object.fromEntries(dims.map(d=>{const vals=records.map(r=>Number(r[d])).filter(Boolean);return[d,vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length):0]}));const strengths=dims.filter(d=>avg[d]>=3).map(d=>labels[d]),focus=dims.filter(d=>avg[d]>0&&avg[d]<3).map(d=>labels[d]);host.innerHTML=`<article class="report-sheet"><div class="report-brand"><span class="brand-mark">T</span><div><strong>Relatório de aprendizagem</strong><small>Identificação exclusivamente numérica</small></div></div><div class="report-identity"><div><span>ESTUDANTE</span><strong>${esc(student)}</strong></div><div><span>TURMA</span><strong>${esc(cls.year)}º ${esc(cls.letter)}</strong></div><div><span>REGISTROS</span><strong>${records.length}</strong></div></div><h3>Indicadores médios</h3><div class="progress-list">${dims.map(d=>`<div><span>${labels[d]}</span><div class="bar"><i style="width:${avg[d]*25}%"></i></div><strong>${avg[d]?avg[d].toFixed(1):"N/O"}</strong></div>`).join("")}</div><div class="report-summary"><div><span>Potencialidades evidenciadas</span><p>${strengths.length?strengths.join(", "):"Ainda são necessárias mais evidências."}</p></div><div><span>Próximos focos</span><p>${focus.length?focus.join(", "):"Manter desafios progressivos e ampliar a autoria."}</p></div></div><h3>Histórico</h3><div class="history">${records.length?records.map(r=>`<div><time>${new Date(r.assessment.date).toLocaleDateString("pt-BR")}</time><strong>${esc(r.plan?.topic||"Plano removido")}</strong><span>${esc(r.plan?.computing?.[0]?.code||"")}</span></div>`).join(""):"<p class='muted'>Nenhuma avaliação registrada para este estudante.</p>"}</div><p class="report-foot">Síntese pedagógica baseada em evidências registradas pelo professor. Não constitui avaliação clínica.</p></article>`;}
  $("#print-report").addEventListener("click",()=>window.print());
  function loadPdi(){const classId=$("#pdi-class").value,student=$("#pdi-student").value,p=state.pdis.find(x=>x.classId===classId&&x.student===student);$("#pdi-barriers").value=p?.barriers||"";$("#pdi-strategies").value=p?.strategies||"";$("#pdi-expression").value=p?.expression||"";$("#pdi-goal").value=p?.goal||"";renderPdiPreview(p,student);}
  function renderPdiPreview(p,student){$("#pdi-preview").innerHTML=p?`<span class="eyebrow">PLANO ATIVO</span><h3>${esc(student)}</h3><div class="pdi-block"><span>Barreiras observadas</span><p>${esc(p.barriers)}</p></div><div class="pdi-block"><span>Apoios que favorecem o acesso</span><p>${esc(p.strategies)}</p></div><div class="pdi-block"><span>Formas de expressão</span><p>${esc(p.expression)}</p></div><div class="goal-box"><span>OBJETIVO MENSURÁVEL</span><strong>${esc(p.goal)}</strong></div><p class="muted">Ao gerar um plano, preserve a habilidade central e altere acesso, participação, tempo e forma de resposta.</p>`:`<div class="empty compact"><span>◇</span><h3>Nenhum PDI para ${esc(student||"este estudante")}</h3><p>Registre necessidades pedagógicas observáveis.</p></div>`;}
  $("#pdi-form").addEventListener("submit",e=>{e.preventDefault();const classId=$("#pdi-class").value,student=$("#pdi-student").value;if(!classId||!student)return toast("Crie uma turma primeiro.");const p={id:uid(),classId,student,barriers:$("#pdi-barriers").value,strategies:$("#pdi-strategies").value,expression:$("#pdi-expression").value,goal:$("#pdi-goal").value,updatedAt:new Date().toISOString()};state.pdis=state.pdis.filter(x=>!(x.classId===classId&&x.student===student));state.pdis.push(p);save();renderPdiPreview(p,student);toast("PDI pedagógico salvo.");});
  $("#export-data").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({app:"Trama",version:1,exportedAt:new Date().toISOString(),data:state},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`trama-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Backup exportado.");});
  $("#import-data").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const parsed=JSON.parse(await f.text());if(parsed.app!=="Trama"||!parsed.data)throw Error();state={...initial,...parsed.data};save();toast("Backup restaurado.");navigate("inicio")}catch{toast("Arquivo de backup inválido.")}e.target.value="";});
  $("#clear-data").addEventListener("click",()=>{if(confirm("Apagar definitivamente todos os planos, turmas, avaliações e PDIs deste navegador?")){state=structuredClone(initial);save();toast("Dados locais apagados.");navigate("inicio")}});

  function updateAll(){
    $("#stat-planos").textContent=state.plans.length;$("#stat-turmas").textContent=state.classes.length;$("#stat-avaliacoes").textContent=state.assessments.length;$("#stat-pdis").textContent=state.pdis.length;
    renderPlans();renderClasses();syncSelectors();renderReport();loadPdi();
  }
  $("#today-label").textContent=new Intl.DateTimeFormat("pt-BR",{dateStyle:"long"}).format(new Date());
  function renderCatalog(){
    const q=normalize($("#catalog-search").value), year=$("#catalog-year").value, axis=$("#catalog-axis").value, component=$("#catalog-component").value; const isComputing=component==="Computação"; $("#catalog-axis").disabled=!isComputing;
    const source=isComputing?window.TRAMA_DATA.computingSkills.map(([code,years,a,text])=>({code,years,axis:a,text,summary:true})):(window.TRAMA_CURRICULUM?.records||[]).filter(x=>x.component===component);
    const skills=source.filter(x=>(year==="all"||x.years.includes(Number(year)))&&(!isComputing||axis==="all"||x.axis===axis)&&(!q||normalize(`${x.code} ${x.axis||""} ${x.text}`).includes(q)));
    $("#catalog-count").textContent=`${skills.length} habilidade${skills.length===1?"":"s"}`;
    const shown=skills.slice(0,120); $("#catalog-list").innerHTML=shown.length?shown.map(x=>`<article class="catalog-card"><div><span class="axis-tag">${esc(x.axis||component)}</span><strong>${esc(x.code)}</strong></div><p>${esc(x.text)}</p><small>${x.years.length===1?`${x.years[0]}º ano`:"6º ao 9º ano"} · ${x.summary?"Código validado · síntese para navegação":"Texto oficial da base local"}</small></article>`).join("")+(skills.length>shown.length?`<p class="catalog-limit">Exibindo 120 de ${skills.length}. Refine a busca para ver resultados mais específicos.</p>`:""):`<div class="empty"><span>⌕</span><h3>Nenhuma habilidade encontrada</h3><p>Tente outro termo ou amplie os filtros.</p></div>`;
  }
  ["catalog-search","catalog-component","catalog-year","catalog-axis"].forEach(id=>$("#"+id).addEventListener(id==="catalog-search"?"input":"change",renderCatalog));
  renderCatalog();
  updateAll();
  if("serviceWorker" in navigator) window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();
