window.TRAMA_DATA = {
  version: "dados-2026.07",
  computingSkills: [
    ["EF69CO01",[6,7,8,9],"Pensamento Computacional","Classificar informações, agrupando-as em coleções (conjuntos) e associando cada coleção a um tipo de dado."],
    ["EF69CO02",[6,7,8,9],"Pensamento Computacional","Elaborar algoritmos que envolvam instruções sequenciais, de repetição e de seleção usando uma linguagem de programação."],
    ["EF69CO03",[6,7,8,9],"Pensamento Computacional","Descrever com precisão a solução de um problema, construindo o programa que implementa a solução descrita."],
    ["EF69CO04",[6,7,8,9],"Pensamento Computacional","Construir soluções de problemas usando a técnica de decomposição e automatizar tais soluções usando uma linguagem de programação."],
    ["EF69CO05",[6,7,8,9],"Pensamento Computacional","Identificar entradas, saídas e respectivos tipos de dados, definindo o problema como uma relação entre entrada e saída."],
    ["EF69CO06",[6,7,8,9],"Pensamento Computacional","Comparar casos de um problema e criar um algoritmo genérico fazendo uso de variáveis (parâmetros)."],
    ["EF69CO07",[6,7,8,9],"Mundo Digital","Entender como a informação é quebrada, transmitida em pacotes por múltiplos equipamentos e reconstruída no destino."],
    ["EF69CO08",[6,7,8,9],"Mundo Digital","Compreender e utilizar formas de armazenar, manipular, compactar e recuperar arquivos, documentos e metadados."],
    ["EF69CO09",[6,7,8,9],"Mundo Digital","Compreender os conceitos de paralelismo, concorrência e armazenamento ou processamento distribuídos."],
    ["EF69CO10",[6,7,8,9],"Mundo Digital","Entender como é a estrutura e o funcionamento da internet."],
    ["EF69CO11",[6,7,8,9],"Cultura Digital","Apresentar conduta e linguagem apropriadas ao se comunicar em ambiente digital, considerando ética e respeito."],
    ["EF69CO12",[6,7,8,9],"Cultura Digital","Analisar criticamente o consumo de tecnologia, sua produção, obsolescência e sustentabilidade."],
    ["EF06CO01",[6],"Pensamento Computacional","Classificar informações em coleções e associar cada coleção a um tipo de dados."],
    ["EF06CO02",[6],"Pensamento Computacional","Elaborar algoritmos com instruções sequenciais, de repetição e de seleção usando uma linguagem de programação."],
    ["EF06CO03",[6],"Pensamento Computacional","Descrever com precisão a solução de um problema e construir o programa que a implementa."],
    ["EF06CO04",[6],"Pensamento Computacional","Construir soluções usando decomposição e automatizá-las em uma linguagem de programação."],
    ["EF06CO05",[6],"Pensamento Computacional","Identificar entradas, saídas e tipos de dados, relacionando-os à definição do problema."],
    ["EF06CO06",[6],"Pensamento Computacional","Criar um algoritmo genérico fazendo uso de variáveis (parâmetros)."],
    ["EF06CO07",[6],"Mundo Digital","Entender o processo de transmissão de dados em pacotes e sua reconstrução no destino."],
    ["EF06CO08",[6],"Mundo Digital","Armazenar, manipular, compactar e recuperar arquivos, documentos e metadados."],
    ["EF06CO09",[6],"Cultura Digital","Apresentar conduta e linguagem apropriadas na comunicação digital, considerando ética e respeito."],
    ["EF06CO10",[6],"Cultura Digital","Analisar criticamente consumo de tecnologia, produção, obsolescência e sustentabilidade."],
    ["EF07CO01",[7],"Pensamento Computacional","Criar soluções usando registros e matrizes unidimensionais e automatizá-las em uma linguagem de programação."],
    ["EF07CO02",[7],"Pensamento Computacional","Analisar programas para detectar e remover erros, ampliando a confiança na sua correção."],
    ["EF07CO03",[7],"Pensamento Computacional","Construir soluções computacionais de problemas de diferentes áreas, individual e colaborativamente."],
    ["EF07CO04",[7],"Pensamento Computacional","Explorar propriedades básicas de grafos."],
    ["EF07CO05",[7],"Pensamento Computacional","Criar algoritmos usando decomposição e reúso de forma colaborativa e cooperativa."],
    ["EF07CO06",[7],"Mundo Digital","Compreender o papel de protocolos para a transmissão de dados."],
    ["EF07CO07",[7],"Mundo Digital","Identificar problemas de segurança cibernética e experimentar formas de proteção."],
    ["EF07CO08",[7],"Cultura Digital","Demonstrar empatia sobre opiniões divergentes na web."],
    ["EF07CO09",[7],"Cultura Digital","Reconhecer e debater sobre cyberbullying."],
    ["EF07CO10",[7],"Cultura Digital","Identificar impactos ambientais do descarte de eletrônicos e sua relação com a sustentabilidade."],
    ["EF07CO11",[7],"Cultura Digital","Criar, documentar e publicar produtos como vídeos, podcasts e websites usando tecnologia."],
    ["EF08CO01",[8],"Pensamento Computacional","Construir soluções usando recursão e automatizá-las em uma linguagem de programação."],
    ["EF08CO02",[8],"Pensamento Computacional","Criar soluções adequadas ao uso de listas, empregando ou não a recursão."],
    ["EF08CO03",[8],"Pensamento Computacional","Utilizar algoritmos clássicos de manipulação sobre listas."],
    ["EF08CO04",[8],"Pensamento Computacional","Construir soluções computacionais articulando saberes de diferentes áreas."],
    ["EF08CO05",[8],"Mundo Digital","Compreender paralelismo, concorrência e armazenamento ou processamento distribuídos."],
    ["EF08CO06",[8],"Mundo Digital","Entender a estrutura e o funcionamento da internet."],
    ["EF08CO07",[8],"Cultura Digital","Compartilhar informações em redes sociais de forma responsável, avaliando sua confiabilidade."],
    ["EF08CO08",[8],"Cultura Digital","Distinguir tipos de dados pessoais solicitados em espaços digitais e os riscos associados."],
    ["EF08CO09",[8],"Cultura Digital","Analisar criticamente políticas e termos de uso de redes sociais e plataformas."],
    ["EF08CO10",[8],"Cultura Digital","Discutir segurança e privacidade relacionadas ao uso de ambientes virtuais."],
    ["EF08CO11",[8],"Cultura Digital","Avaliar precisão, relevância, adequação, abrangência e vieses em fontes eletrônicas."],
    ["EF09CO01",[9],"Pensamento Computacional","Criar soluções usando árvores e grafos e automatizá-las em uma linguagem de programação."],
    ["EF09CO02",[9],"Pensamento Computacional","Construir soluções computacionais de diferentes áreas selecionando estruturas e técnicas adequadas."],
    ["EF09CO03",[9],"Pensamento Computacional","Usar autômatos para descrever comportamentos e automatizá-los com programação baseada em eventos."],
    ["EF09CO04",[9],"Mundo Digital","Compreender o funcionamento de malwares e outros ataques cibernéticos."],
    ["EF09CO05",[9],"Mundo Digital","Analisar técnicas de criptografia para armazenamento e transmissão de dados."],
    ["EF09CO06",[9],"Cultura Digital","Analisar problemas sociais da cidade e do estado em ambientes digitais, propondo soluções."],
    ["EF09CO07",[9],"Cultura Digital","Avaliar implicações políticas, socioambientais e culturais das tecnologias digitais."],
    ["EF09CO08",[9],"Cultura Digital","Discutir equidade, acesso e poder na distribuição global de recursos de computação."],
    ["EF09CO09",[9],"Cultura Digital","Criar ou utilizar conteúdo digital compreendendo direitos autorais e de uso de imagem."],
    ["EF09CO10",[9],"Cultura Digital","Avaliar veracidade, credibilidade, relevância e propósito de informações em diferentes formatos."]
  ],
  topics: [
    { terms:["variavel","variáveis","variável","algebra"], component:"Matemática", years:[7], subject:{code:"EF07MA13",text:"Compreender a ideia de variável para expressar relações entre grandezas, diferenciando-a da ideia de incógnita."}, computing:[{code:"EF69CO06",axis:"Pensamento Computacional",text:"Criar algoritmos fazendo uso de variáveis (parâmetros) para tratar casos de forma genérica."},{code:"EF07CO03",axis:"Pensamento Computacional",text:"Construir soluções computacionais articulando saberes de diferentes áreas."}], confidence:"Direta", tech:"Construir no Scratch uma calculadora ou jogo em que variáveis controlem pontuação, tempo e estados.", unplugged:"Usar envelopes identificados como variáveis; os grupos alteram valores seguindo cartões de regras e registram os estados.", project:"Simulador interativo de situações algébricas do cotidiano." },
    { terms:["fração","frações","proporcao","proporção","escala"], component:"Matemática", years:[6], subject:{code:"EF06MA21",text:"Construir figuras semelhantes em ampliação e redução usando malhas, plano cartesiano ou tecnologias digitais."}, computing:[{code:"EF06CO02",axis:"Pensamento Computacional",text:"Elaborar algoritmos com instruções sequenciais, repetição e seleção."},{code:"EF06CO05",axis:"Pensamento Computacional",text:"Identificar entradas, saídas e tipos de dados de um problema."}], confidence:"Interdisciplinar forte", tech:"Programar a ampliação e a redução de uma figura em uma malha digital, testando diferentes fatores.", unplugged:"Executar um algoritmo em cartões para ampliar desenhos em papel quadriculado e conferir os resultados.", project:"Galeria de padrões ampliados com explicação matemática e algoritmo." },
    { terms:["plano cartesiano","coordenada","coordenadas","movimento"], component:"Matemática", years:[6,7,8], subject:{code:"EF08MA12",text:"Representar a relação entre grandezas por sentença algébrica e no plano cartesiano."}, computing:[{code:"EF69CO02",axis:"Pensamento Computacional",text:"Elaborar algoritmos com sequência, repetição e seleção."},{code:"EF08CO04",axis:"Pensamento Computacional",text:"Construir soluções computacionais articulando diferentes áreas."}], confidence:"Interdisciplinar forte", tech:"Criar uma animação controlada por coordenadas e registrar como mudanças em X e Y alteram o movimento.", unplugged:"Usar uma malha no chão; colegas executam sequências de deslocamento e depuram comandos incorretos.", project:"Mapa interativo acessível da escola." },
    { terms:["publicidade","propaganda","midia","mídia","multissemiose"], component:"Língua Portuguesa", years:[6,7,8,9], subject:{code:"EF69LP02",text:"Analisar e comparar peças publicitárias em diferentes mídias, considerando semioses, público e objetivos."}, computing:[{code:"EF07CO11",axis:"Cultura Digital",text:"Criar, documentar e publicar produtos digitais com recursos de tecnologia."},{code:"EF69CO11",axis:"Cultura Digital",text:"Comunicar-se em ambiente digital com ética e respeito."}], confidence:"Direta", tech:"Analisar campanhas digitais e criar uma peça multimídia que explicite público, intenção e escolhas visuais.", unplugged:"Desmontar anúncios impressos em cartões de texto, imagem, público, intenção e recurso persuasivo.", project:"Campanha de uso ético e responsável da tecnologia." },
    { terms:["fake news","fact-checking","fontes","argumento","argumentação","confiabilidade"], component:"Língua Portuguesa", years:[8,9], subject:{code:"EF89LP04",text:"Avaliar teses, opiniões, argumentos e contra-argumentos, posicionando-se de forma sustentada."}, computing:[{code:"EF08CO11",axis:"Cultura Digital",text:"Avaliar precisão, relevância, adequação, abrangência e vieses de fontes eletrônicas."},{code:"EF08CO07",axis:"Cultura Digital",text:"Compartilhar informações responsavelmente e avaliar sua confiabilidade."}], confidence:"Direta", tech:"Realizar uma oficina de verificação de fatos com protocolo de leitura lateral e registro das fontes.", unplugged:"Comparar dossiês impressos com autoria, evidências e contexto; classificar a confiabilidade justificando critérios.", project:"Agência escolar de checagem e cidadania digital." },
    { terms:["algoritmo","sequencia","sequência","repetição","condicional","programação"], component:"*", years:[6,7,8,9], subject:null, computing:[{code:"EF69CO02",axis:"Pensamento Computacional",text:"Elaborar algoritmos com instruções sequenciais, de repetição e de seleção usando linguagem de programação."},{code:"EF69CO03",axis:"Pensamento Computacional",text:"Descrever com precisão uma solução e construir o programa que a implementa."}], confidence:"Direta em Computação", tech:"Criar e testar um programa curto, registrando entradas, decisões, repetições e saídas.", unplugged:"Representar o algoritmo com cartões; outro grupo executa literalmente e devolve erros para depuração.", project:"Solução automatizada para um problema real do componente selecionado." },
    { terms:["internet","rede","redes"], component:"*", years:[6,7,8,9], subject:null, computing:[{code:"EF69CO10",axis:"Mundo Digital",text:"Entender a estrutura e o funcionamento da internet."},{code:"EF69CO07",axis:"Mundo Digital",text:"Entender como dados são divididos, transmitidos em pacotes e reconstruídos no destino."}], confidence:"Transversal", tech:"Simular o envio de uma mensagem em pacotes e investigar os elementos do percurso na internet.", unplugged:"Distribuir partes de uma mensagem por diferentes rotas da sala, com protocolos de identificação e remontagem.", project:"Mapa explicativo: o caminho de uma informação na internet." }
  ],
  defaults: {
    computing:[{code:"EF69CO03",axis:"Pensamento Computacional",text:"Descrever com precisão a solução de um problema e construir um programa que a implemente."},{code:"EF69CO04",axis:"Pensamento Computacional",text:"Construir soluções por decomposição e automatizá-las."}],
    tech:"Investigar o assunto, decompor um problema relacionado e construir uma produção digital que apresente a solução.",
    unplugged:"Modelar o problema com cartões, fluxograma e representação física; testar e revisar a sequência criada.",
    project:"Produto autoral que comunique uma solução relacionada ao assunto para a comunidade escolar."
  }
};
